workflows:
  ios-testflight-workflow:
    name: iOS TestFlight Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      groups:
        - apple_credentials
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
    scripts:
      - name: Set up code signing settings
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.rtvoorhees.esp32_ios_reader" --type IOS_APP_STORE --create
          keychain add-certificates
      - name: Force Rewrite Frozen Xcode Build Metadata
        script: |
          # Wipes out any cached data and forces a hard text replacement inside native iOS files
          flutter clean
          find ios -type f \( -name "*.xcconfig" -o -name "*.sh" -o -name "*.pbxproj" -o -name "*.plist" \) -exec sed -i '' 's/FLUTTER_BUILD_NUMBER=24/FLUTTER_BUILD_NUMBER=125/g' {} +
          find ios -type f \( -name "*.xcconfig" -o -name "*.sh" -o -name "*.pbxproj" -o -name "*.plist" \) -exec sed -i '' 's/CURRENT_PROJECT_VERSION = 24/CURRENT_PROJECT_VERSION = 125/g' {} +
          find ios -type f \( -name "*.xcconfig" -o -name "*.sh" -o -name "*.pbxproj" -o -name "*.plist" \) -exec sed -i '' 's/>24</>125</g' {} +
      - name: Flutter build App Store IPA
        script: |
          flutter pub get
          flutter build ipa --release --build-number=125
    artifacts:
      - build/ios/ipa/*.ipa
