workflows:
  ios-testflight-workflow:
    name: iOS TestFlight Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
    scripts:
      - name: Set up code signing settings
        script: |
          keychain initialize
          codemagic-initialize-signing-files
          keychain add-certificates
      - name: Wipe Cached Build Settings
        script: |
          # Forcefully clean out frozen Flutter variables and lockfiles
          flutter clean
          rm -rf ios/Flutter/Generated.xcconfig
          rm -rf ios/Flutter/flutter_export_environment.sh
      - name: Flutter build App Store IPA
        script: |
          flutter pub get
          flutter build ipa --release --build-number=95
    artifacts:
      - build/ios/ipa/*.ipa
